### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper-parser#41]
Upgrade project dependencies to latest versions

**Comment by hkeeler** [comment]
I took a quick stab at upgrading the dependencies.  Unfortunately, with the upgrade of [`usaddress`](https://github.com/datamade/usaddress), two of the tests now fail.  Basically, two tests that both cover cases where the address couldn't be parsed before, now no longer fail.  I'll have to look into whether those types of failures no longer occur, or if I just need to find different addresses to get it into the same state.

```
======================================================================
ERROR: API: POST /parse -> 200 with good and bad address strings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/keelerh/Projects/grasshopper-parser/.tox/py27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/keelerh/Projects/grasshopper-parser/tests/tests.py", line 323, in test_parse_batch_with_failed_parse
    assert_equals(resp_data['failed'][0], '5 Arapahoe Plaza El Paso TX 88530')
IndexError: list index out of range

======================================================================
FAIL: API: GET /parse -> 400 with 'method=tag' and address that raises RepeatedLabelError
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/keelerh/Projects/grasshopper-parser/.tox/py27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/keelerh/Projects/grasshopper-parser/tests/tests.py", line 279, in test_parse_fail_with_repeated_label_error
    assert_equals(400, rv.status_code)
AssertionError: 400 != 200
```
